name: "set output"

on:
  push:
    branches:
      - main

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: set result
      run: |
        echo "hoge" >> output.txt
        echo "hoge" >> output.txt
        echo "hoge" >> output.txt
        echo "result<EOF" >> $GITHUB_TOKEN
        cat output.txt >> $GITHUB_TOKEN
        echo "EOF" >> $GITHUB_TOKEN
    - name: get result
      run: echo "${{ steps.edit.outputs.greeting }}"
