name: "set output"

on:
  push:
    branches:
      - main

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/github-script@v6
      id: edit
      with:
        script: |
          const name = 'greeting'
          const value = 'Hello\nWorld'
          core.setOutput(name, value)
    - name: get result
      run: echo "${{ steps.edit.outputs.greeting }}"
