name: "set output"

on:
  push:
    branches:
      - main

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: set result
      run: |
        ruby main.rb > output.txt 2>&1 || echo $? > exitcode.txt
        echo "result<<EOF" >> $GITHUB_OUTPUT
        cat output.txt >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    - name: get result
      run: echo "${{ steps.edit.outputs.greeting }}"
